import {
  Activity,
  Bell,
  Building,
  Building2,
  CalendarDays,
  Check,
  ChevronRight,
  CircleDollarSign,
  DollarSign,
  Edit3,
  ExternalLink,
  Eye,
  Factory,
  FileText,
  Filter,
  Landmark,
  LayoutDashboard,
  LogOut,
  MapPin,
  Menu,
  MessageSquareWarning,
  MoreHorizontal,
  Package,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Tags,
  Trash2,
  Users,
  Waves,
  X,
  XCircle,
} from 'lucide-react';

const icons = {
  activity: Activity,
  bell: Bell,
  building: Building,
  'building-2': Building2,
  calendar: CalendarDays,
  check: Check,
  chevron: ChevronRight,
  'circle-dollar-sign': CircleDollarSign,
  'dollar-sign': DollarSign,
  edit: Edit3,
  external: ExternalLink,
  eye: Eye,
  factory: Factory,
  'file-text': FileText,
  filter: Filter,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  logout: LogOut,
  'map-pin': MapPin,
  'message-square-warning': MessageSquareWarning,
  menu: Menu,
  more: MoreHorizontal,
  package: Package,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  star: Star,
  tags: Tags,
  trash: Trash2,
  users: Users,
  waves: Waves,
  close: X,
  'x-circle': XCircle,
};

export const AdminIcon = ({ name, size = 18, strokeWidth = 2, ...props }) => {
  const Icon = icons[name] || LayoutDashboard;
  return <Icon size={size} strokeWidth={strokeWidth} {...props} />;
};
