// ─── Delay helper (giả lập network latency) ─────────────────────────────────
export const delay = (ms = 400) => new Promise((resolve) => setTimeout(resolve, ms));

// ─── Mock Rooms ──────────────────────────────────────────────────────────────
export const MOCK_ROOMS = [
  {
    id: 1,
    code: 'TRO-001',
    name: 'Phòng trọ Lê Lợi',
    address: 'Lê Lợi, Thủ Đức',
    area: 20,
    capacity: 2,
    amenities: ['Wifi', 'Điện'],
    price: 2500000,
    status: 'available', // available | rented | negotiating
    images: [],
    description: 'Phòng sạch sẽ, thoáng mát, gần chợ, có wifi tốc độ cao.',
    lat: 10.8579,
    lng: 106.7800,
    bedroom_count: 1,
    room_type: 'Phòng trọ',
    district: 'Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-01T08:00:00Z',
  },
  {
    id: 2,
    code: 'TRO-002',
    name: 'Mini studio Nguyễn Trãi',
    address: 'Nguyễn Trãi, Q.1',
    area: 35,
    capacity: 1,
    amenities: ['Máy lạnh'],
    price: 4200000,
    status: 'rented',
    images: [],
    description: 'Studio đẹp, đầy đủ nội thất, gần trung tâm.',
    lat: 10.7769,
    lng: 106.6992,
    bedroom_count: 1,
    room_type: 'Studio',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-04-15T10:00:00Z',
  },
  {
    id: 3,
    code: 'TRO-003',
    name: 'Phòng full NT Q.1',
    address: 'Nguyễn Trãi, Q.1',
    area: 45,
    capacity: 2,
    amenities: ['Máy lạnh', 'Full NT'],
    price: 5800000,
    status: 'available',
    images: [],
    description: 'Căn hộ đầy đủ nội thất, view đẹp, an ninh tốt.',
    lat: 10.7750,
    lng: 106.7000,
    bedroom_count: 2,
    room_type: 'Căn hộ',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-10T09:00:00Z',
  },
  {
    id: 4,
    code: 'TRO-004',
    name: 'Căn hộ mini Q.7',
    address: 'Nguyễn Thị Thập, Q.7',
    area: 28,
    capacity: 1,
    amenities: ['Bếp riêng'],
    price: 3800000,
    status: 'negotiating',
    images: [],
    description: 'Căn hộ mini tiện nghi, có bếp riêng, yên tĩnh.',
    lat: 10.7311,
    lng: 106.7200,
    bedroom_count: 1,
    room_type: 'Căn hộ mini',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-05T14:00:00Z',
  },
  {
    id: 5,
    code: 'TRO-005',
    name: 'Trọ SV Làng ĐH',
    address: 'Khu phố 6, Thủ Đức',
    area: 18,
    capacity: 2,
    amenities: ['Wifi'],
    price: 1800000,
    status: 'available',
    images: [],
    description: 'Phòng giá rẻ gần làng đại học, phù hợp sinh viên.',
    lat: 10.8700,
    lng: 106.8020,
    bedroom_count: 1,
    room_type: 'Phòng trọ',
    district: 'Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-20T11:00:00Z',
  },
];

export const buildRoom = (raw) => ({
  id: raw.id,
  code: raw.code || `TRO-${String(raw.id).padStart(3, '0')}`,
  name: raw.name,
  address: raw.address,
  area: raw.area,
  capacity: raw.capacity,
  amenities: raw.amenities || [],
  price: raw.price,
  status: raw.status || 'available',
  images: raw.images || [],
  description: raw.description || '',
  lat: raw.lat,
  lng: raw.lng,
  bedroom_count: raw.bedroom_count || 1,
  room_type: raw.room_type || 'Phòng trọ',
  district: raw.district || '',
  city: raw.city || '',
  created_at: raw.created_at || new Date().toISOString(),
});

export const findRoomById = (id) =>
  MOCK_ROOMS.find((r) => r.id === Number(id)) || null;

// ─── Mock Packages ────────────────────────────────────────────────────────────
export const MOCK_PACKAGES = [
  {
    id: 1,
    name: 'Cơ bản',
    tier: 'basic',
    price: 49000,
    unit: 'tháng',
    isFeatured: false,
    badge: null,
    features: [
      { label: 'Đăng tối đa 3 bài / tháng', included: true },
      { label: 'Hiển thị trong kết quả tìm kiếm', included: true },
      { label: 'Đẩy tin nổi bật 5 lần / tháng', included: false },
      { label: 'Không có badge xác thực', included: false },
    ],
    ctaLabel: 'Thử miễn phí',
  },
  {
    id: 2,
    name: 'Pro',
    tier: 'pro',
    price: 1000000,
    unit: 'tháng',
    isFeatured: true,
    badge: 'hot',
    features: [
      { label: 'Đăng không giới hạn bài', included: true },
      { label: 'Hiển thị trong kết quả tìm kiếm', included: true },
      { label: 'Đẩy tin nổi bật 5 lần / tháng', included: true },
      { label: 'Ưu tiên hiển thị tìm kiếm', included: true },
      { label: 'Huy hiệu vip', included: true },
    ],
    ctaLabel: 'Thử miễn phí',
  },
  {
    id: 3,
    name: 'VIP',
    tier: 'vip',
    price: 10000000,
    unit: 'tháng',
    isFeatured: false,
    badge: 'Pro',
    features: [
      { label: 'Các đặc quyền tương tự hot', included: true },
      { label: 'Huy hiệu Pro', included: true },
      { label: 'Đánh dấu trọ uy tín', included: true },
    ],
    ctaLabel: 'Thử miễn phí',
  },
];

// ─── Mock Notifications ───────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: 'subscription',
    title: 'Gói Đăng Tin',
    message: 'Sẽ Hết Hạn Vào 2 Ngày Nữa',
    isAlert: true,
    alertLabel: 'Chi Tiết',
    createdAt: '2026-05-30T08:00:00Z',
    read: false,
  },
  {
    id: 2,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-29T10:00:00Z',
    read: false,
  },
  {
    id: 3,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-28T14:00:00Z',
    read: true,
  },
  {
    id: 4,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-27T09:00:00Z',
    read: true,
  },
  {
    id: 5,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-26T16:00:00Z',
    read: true,
  },
  {
    id: 6,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-25T11:00:00Z',
    read: true,
  },
  {
    id: 7,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-24T10:00:00Z',
    read: true,
  },
];

// ─── Mock Landlord Profile ────────────────────────────────────────────────────
export const MOCK_LANDLORD_PROFILE = {
  id: 1,
  display_name: 'Nguyễn Văn Hảo',
  nickname: 'Hảo',
  role: 'Chủ Trọ Vui Vẻ',
  avatar: null,
  bio: '"Tôi Có 5 Năm Kinh Nghiệm Quản Lý Phòng Trọ Tại Khu Vực Làng Đại Học. Luôn Hỗ Trợ Người Thuê Nhiệt Tình Và Chu Đáo."',
  dob: '18-08-2004',
  gender: 'Nam',
  status: '',
  phone: '',
  facebook: '',
  zalo: '',
  location: 'Linh Trung, Thủ Đức',
  hometown: '',
  cccd_verified: false,
  scores: {
    posts: 100,
    likes: 100,
    connections: 100,
    verified: 100,
  },
};
