// ─── Delay helper (giả lập network latency) ─────────────────────────────────
export const delay = (ms = 400) => new Promise((resolve) => setTimeout(resolve, ms));

// ─── Mock Rooms ──────────────────────────────────────────────────────────────
export const MOCK_ROOMS = [
  {
    id: 1,
    code: 'TRO-001',
    name: 'Phòng trọ Lê Lợi',
    address: 'Lê Lợi, Thủ Đức',
    area: 20,
    capacity: 2,
    amenities: ['Wifi', 'Điện'],
    price: 2500000,
    status: 'available', // available | rented | negotiating
    images: [],
    description: 'Phòng sạch sẽ, thoáng mát, gần chợ, có wifi tốc độ cao.',
    lat: 10.8579,
    lng: 106.7800,
    bedroom_count: 1,
    room_type: 'Phòng trọ',
    district: 'Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-01T08:00:00Z',
  },
  {
    id: 2,
    code: 'TRO-002',
    name: 'Mini studio Nguyễn Trãi',
    address: 'Nguyễn Trãi, Q.1',
    area: 35,
    capacity: 1,
    amenities: ['Máy lạnh'],
    price: 4200000,
    status: 'rented',
    images: [],
    description: 'Studio đẹp, đầy đủ nội thất, gần trung tâm.',
    lat: 10.7769,
    lng: 106.6992,
    bedroom_count: 1,
    room_type: 'Studio',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-04-15T10:00:00Z',
  },
  {
    id: 3,
    code: 'TRO-003',
    name: 'Phòng full NT Q.1',
    address: 'Nguyễn Trãi, Q.1',
    area: 45,
    capacity: 2,
    amenities: ['Máy lạnh', 'Full NT'],
    price: 5800000,
    status: 'available',
    images: [],
    description: 'Căn hộ đầy đủ nội thất, view đẹp, an ninh tốt.',
    lat: 10.7750,
    lng: 106.7000,
    bedroom_count: 2,
    room_type: 'Căn hộ',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-10T09:00:00Z',
  },
  {
    id: 4,
    code: 'TRO-004',
    name: 'Căn hộ mini Q.7',
    address: 'Nguyễn Thị Thập, Q.7',
    area: 28,
    capacity: 1,
    amenities: ['Bếp riêng'],
    price: 3800000,
    status: 'negotiating',
    images: [],
    description: 'Căn hộ mini tiện nghi, có bếp riêng, yên tĩnh.',
    lat: 10.7311,
    lng: 106.7200,
    bedroom_count: 1,
    room_type: 'Căn hộ mini',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-05T14:00:00Z',
  },
  {
    id: 5,
    code: 'TRO-005',
    name: 'Trọ SV Làng ĐH',
    address: 'Khu phố 6, Thủ Đức',
    area: 18,
    capacity: 2,
    amenities: ['Wifi'],
    price: 1800000,
    status: 'available',
    images: [],
    description: 'Phòng giá rẻ gần làng đại học, phù hợp sinh viên.',
    lat: 10.8700,
    lng: 106.8020,
    bedroom_count: 1,
    room_type: 'Phòng trọ',
    district: 'Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    created_at: '2026-05-20T11:00:00Z',
  },
];

export const buildRoom = (raw) => ({
  id: raw.id,
  code: raw.code || `TRO-${String(raw.id).padStart(3, '0')}`,
  name: raw.name,
  address: raw.address,
  area: raw.area,
  capacity: raw.capacity,
  amenities: raw.amenities || [],
  price: raw.price,
  status: raw.status || 'available',
  images: raw.images || [],
  description: raw.description || '',
  lat: raw.lat,
  lng: raw.lng,
  bedroom_count: raw.bedroom_count || 1,
  room_type: raw.room_type || 'Phòng trọ',
  district: raw.district || '',
  city: raw.city || '',
  created_at: raw.created_at || new Date().toISOString(),
});

export const findRoomById = (id) =>
  MOCK_ROOMS.find((r) => r.id === Number(id)) || null;

// ─── Mock Packages ────────────────────────────────────────────────────────────
export const MOCK_PACKAGES = [
  {
    id: 1,
    name: 'Cơ bản',
    tier: 'basic',
    price: 49000,
    unit: 'tháng',
    durationLabel: '1 tháng',
    description: 'Gói khởi đầu cho chủ trọ mới đăng ít bài.',
    isFeatured: false,
    badge: null,
    features: [
      { label: 'Đăng tối đa 3 bài / tháng', included: true },
      { label: 'Hiển thị trong kết quả tìm kiếm', included: true },
      { label: 'Đẩy tin nổi bật 5 lần / tháng', included: false },
      { label: 'Không có badge xác thực', included: false },
    ],
    limits: {
      postsLimit: 3,
      boostLimit: 0,
      photoLimit: 15,
      badge: 'Không có',
    },
    ctaLabel: 'Chọn gói',
  },
  {
    id: 2,
    name: 'Pro',
    tier: 'pro',
    price: 1000000,
    unit: 'tháng',
    durationLabel: '1 tháng',
    description: 'Tăng hiển thị và mở khóa công cụ quảng bá bài đăng.',
    isFeatured: true,
    badge: 'hot',
    features: [
      { label: 'Đăng không giới hạn bài', included: true },
      { label: 'Hiển thị trong kết quả tìm kiếm', included: true },
      { label: 'Đẩy tin nổi bật 5 lần / tháng', included: true },
      { label: 'Ưu tiên hiển thị tìm kiếm', included: true },
      { label: 'Huy hiệu Pro trên phòng trọ', included: true },
    ],
    limits: {
      postsLimit: null,
      boostLimit: 5,
      photoLimit: 50,
      badge: 'Pro',
    },
    ctaLabel: 'Chọn gói',
  },
  {
    id: 3,
    name: 'VIP',
    tier: 'vip',
    price: 5000000,
    unit: 'tháng',
    durationLabel: '1 tháng',
    description: 'Gói ưu tiên cao nhất cho chủ trọ cần phủ hiển thị mạnh.',
    isFeatured: false,
    badge: 'VIP',
    features: [
      { label: 'Đăng không giới hạn bài', included: true },
      { label: 'Hiển thị trong kết quả tìm kiếm', included: true },
      { label: 'Đẩy tin nổi bật 5 lần / tháng', included: true },
      { label: 'Ưu tiên hiển thị tìm kiếm', included: true },
      { label: 'Huy hiệu VIP trên phòng trọ', included: true },
    ],
    limits: {
      postsLimit: null,
      boostLimit: 5,
      photoLimit: 80,
      badge: 'VIP',
    },
    ctaLabel: 'Chọn gói',
  },
];

export const findPackageById = (id) =>
  MOCK_PACKAGES.find((pkg) => pkg.id === Number(id)) || null;

// ─── Mock Notifications ───────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: 'subscription',
    title: 'Gói Đăng Tin',
    message: 'Sẽ Hết Hạn Vào 2 Ngày Nữa',
    isAlert: true,
    alertLabel: 'Chi Tiết',
    createdAt: '2026-05-30T08:00:00Z',
    read: false,
  },
  {
    id: 2,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-29T10:00:00Z',
    read: false,
  },
  {
    id: 3,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-28T14:00:00Z',
    read: true,
  },
  {
    id: 4,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-27T09:00:00Z',
    read: true,
  },
  {
    id: 5,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-26T16:00:00Z',
    read: true,
  },
  {
    id: 6,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-25T11:00:00Z',
    read: true,
  },
  {
    id: 7,
    type: 'complaint',
    title: 'Khiếu Nại',
    message: 'Cảnh Báo Khiếu Nại Cơ Sở Vật Chất. Vui Lòng Kiểm Tra Email Để Nắm Rõ Thông Tin',
    createdAt: '2026-05-24T10:00:00Z',
    read: true,
  },
];

// ─── Mock Landlord Profile ────────────────────────────────────────────────────
export const MOCK_LANDLORD_PROFILE = {
  id: 1,
  display_name: 'Nguyễn Văn Hảo',
  nickname: 'Hảo',
  role: 'Chủ Trọ Vui Vẻ',
  avatar: null,
  bio: '"Tôi Có 5 Năm Kinh Nghiệm Quản Lý Phòng Trọ Tại Khu Vực Làng Đại Học. Luôn Hỗ Trợ Người Thuê Nhiệt Tình Và Chu Đáo."',
  dob: '18-08-2004',
  gender: 'Nam',
  status: '',
  phone: '',
  facebook: '',
  zalo: '',
  location: 'Linh Trung, Thủ Đức',
  hometown: '',
  cccd_verified: false,
  scores: {
    posts: 100,
    likes: 100,
    connections: 100,
    verified: 100,
  },
};

// ─── Mock Landlord Posts ──────────────────────────────────────────────────────
export const MOCK_LANDLORD_POSTS = [
  {
    id: 1,
    code: 'P001',
    title: 'Top 10 phòng trọ đẹp nhất Quận 1 TP.HCM giá dưới 5 triệu',
    author: 'Trần Hoa',
    publishedAt: '2025-07-01',
    status: 'pending',
    views: 1200,
    likes: 88,
    comments: 23,
    boostDaysLeft: 0,
    boostTotalDays: 0,
    badges: [],
  },
  {
    id: 2,
    code: 'P002',
    title: 'Kinh nghiệm thuê phòng trọ an toàn cho sinh viên mới lên thành phố',
    author: 'Nguyễn Minh',
    publishedAt: '2025-06-29',
    status: 'approved',
    views: 4600,
    likes: 312,
    comments: 67,
    boostDaysLeft: 0,
    boostTotalDays: 0,
    badges: [],
  },
  {
    id: 3,
    code: 'P003',
    title: 'Review căn hộ dịch vụ Bình Thạnh - Đáng tiền hay không?',
    author: 'Lê Tuấn',
    publishedAt: '2025-06-28',
    status: 'boosted',
    views: 9900,
    likes: 541,
    comments: 102,
    boostDaysLeft: 3,
    boostTotalDays: 7,
    badges: ['Cao', 'Trang chủ', 'Top Trending'],
  },
  {
    id: 4,
    code: 'P004',
    title: 'Cần lưu ý gì khi ký hợp đồng thuê trọ lần đầu?',
    author: 'Nguyễn Vy',
    publishedAt: '2025-06-27',
    status: 'rejected',
    views: 380,
    likes: 21,
    comments: 5,
    boostDaysLeft: 0,
    boostTotalDays: 0,
    badges: [],
  },
  {
    id: 5,
    code: 'P005',
    title: '5 khu vực có phòng trọ giá rẻ, tiện lợi tại Hà Nội 2025',
    author: 'Phạm Nam',
    publishedAt: '2025-06-26',
    status: 'pending',
    views: 720,
    likes: 45,
    comments: 12,
    boostDaysLeft: 0,
    boostTotalDays: 0,
    badges: [],
  },
  {
    id: 6,
    code: 'P006',
    title: 'Thuê nhà nguyên căn hay thuê phòng trọ - Lựa chọn nào hợp lý?',
    author: 'Hoàng Sơn',
    publishedAt: '2025-06-25',
    status: 'approved',
    views: 2100,
    likes: 178,
    comments: 34,
    boostDaysLeft: 0,
    boostTotalDays: 0,
    badges: [],
  },
  {
    id: 7,
    code: 'P007',
    title: 'Hướng dẫn tìm phòng trọ qua bản đồ thông minh TrọNhanh',
    author: 'Trần Hoa',
    publishedAt: '2025-06-24',
    status: 'boosted',
    views: 6300,
    likes: 420,
    comments: 88,
    boostDaysLeft: 5,
    boostTotalDays: 7,
    badges: ['Trung bình', 'Trang chủ', 'Đề xuất'],
  },
  {
    id: 8,
    code: 'P008',
    title: 'Cách tiết kiệm điện nước tối đa cho sinh viên thuê trọ',
    author: 'Nguyễn Hân',
    publishedAt: '2025-06-23',
    status: 'boosted',
    views: 4500,
    likes: 210,
    comments: 45,
    boostDaysLeft: 1,
    boostTotalDays: 3,
    badges: ['Nhẹ', 'Trang chủ'],
  },
];

export const POST_STATUS_LABELS = {
  pending: 'Chờ duyệt',
  approved: 'Đã duyệt',
  boosted: 'Đang đẩy nổi bật',
  rejected: 'Từ chối',
};

export const MOCK_POST_ENGAGEMENT = [
  { label: 'T2', views: 2900, likes: 88 },
  { label: 'T3', views: 4200, likes: 120 },
  { label: 'T4', views: 3800, likes: 98 },
  { label: 'T5', views: 5200, likes: 165 },
  { label: 'T6', views: 4800, likes: 140 },
  { label: 'T7', views: 6100, likes: 190 },
  { label: 'CN', views: 4100, likes: 118 },
];

// ─── Mock Package Management ─────────────────────────────────────────────────
export const MOCK_PACKAGE_HISTORY = [
  {
    id: 'INV-2025-0042',
    packageId: 3,
    packageName: 'VIP',
    tier: 'vip',
    price: 5000000,
    purchaseDate: '2025-03-13',
    expiredDate: '2026-03-13',
    status: 'expired',
    period: '1 tháng',
    paymentMethod: 'Chuyển khoản',
    autoRenew: false,
  },
  {
    id: 'INV-2025-0038',
    packageId: 3,
    packageName: 'VIP',
    tier: 'vip',
    price: 5000000,
    purchaseDate: '2025-03-13',
    expiredDate: '2026-03-13',
    status: 'expired',
    period: '1 tháng',
    paymentMethod: 'Chuyển khoản',
    autoRenew: false,
  },
  {
    id: 'INV-2025-0031',
    packageId: 3,
    packageName: 'VIP',
    tier: 'vip',
    price: 5000000,
    purchaseDate: '2025-03-13',
    expiredDate: '2026-03-13',
    status: 'expired',
    period: '1 tháng',
    paymentMethod: 'Chuyển khoản',
    autoRenew: false,
  },
  {
    id: 'INV-2025-0028',
    packageId: 3,
    packageName: 'VIP',
    tier: 'vip',
    price: 5000000,
    purchaseDate: '2025-03-13',
    expiredDate: '2026-03-13',
    status: 'expired',
    period: '1 tháng',
    paymentMethod: 'Chuyển khoản',
    autoRenew: false,
  },
  {
    id: 'INV-2025-0024',
    packageId: 3,
    packageName: 'VIP',
    tier: 'vip',
    price: 5000000,
    purchaseDate: '2025-03-13',
    expiredDate: '2026-03-13',
    status: 'expired',
    period: '1 tháng',
    paymentMethod: 'Chuyển khoản',
    autoRenew: false,
  },
  {
    id: 'INV-2025-0019',
    packageId: 3,
    packageName: 'VIP',
    tier: 'vip',
    price: 5000000,
    purchaseDate: '2025-03-13',
    expiredDate: '2026-03-13',
    status: 'expired',
    period: '1 tháng',
    paymentMethod: 'Chuyển khoản',
    autoRenew: false,
  },
];

export const MOCK_PACKAGE_USAGE = {
  id: 'INV-2025-0042',
  packageId: 3,
  packageName: 'VIP',
  tier: 'vip',
  price: 5000000,
  period: '1 tháng',
  purchaseDate: '2025-03-13',
  expiredDate: '2026-03-13',
  status: 'expired',
  autoRenew: false,
  paymentMethod: 'Chuyển khoản',
  postsUsed: 24,
  postsLimit: null,
  activePosts: 6,
  boostUsed: 4,
  boostLimit: 5,
  photoUsed: 38,
  photoLimit: 80,
  roomViews: 1284,
  remainingDays: 0,
  benefits: [
    { label: 'Đăng không giới hạn bài', included: true },
    { label: 'Ưu tiên hiển thị tìm kiếm', included: true },
    { label: 'Đẩy tin nổi bật 5 lần/tháng', included: true },
    { label: 'Ưu tiên hiển thị tìm kiếm', included: true },
    { label: 'Huy hiệu VIP trên phòng trọ', included: true },
  ],
  timeline: [
    {
      id: 1,
      title: 'Kích hoạt gói VIP',
      description: '13/03/2025 lúc 10:24 · Thanh toán thành công',
      tone: 'success',
    },
    {
      id: 2,
      title: 'Sử dụng 24 bài đăng',
      description: 'Trong suốt kỳ gói · bài gần nhất 02/03/2026',
      tone: 'success',
    },
    {
      id: 3,
      title: 'Gói hết hạn',
      description: '13/03/2026 lúc 23:59 · Chưa gia hạn',
      tone: 'danger',
    },
    {
      id: 4,
      title: 'Chờ gia hạn',
      description: 'Gia hạn để tiếp tục đăng bài không giới hạn',
      tone: 'muted',
    },
  ],
};

// ─── Mock Statistics ─────────────────────────────────────────────────────────
export const MOCK_LANDLORD_STATS = {
  summary: [
    { id: 'posts', label: 'Tổng bài đăng', value: 12, change: '+2 mới', icon: 'file', tone: 'green' },
    { id: 'rooms', label: 'Tổng số phòng', value: 34, change: '8 trống', icon: 'home', tone: 'muted' },
    { id: 'views', label: 'Lượt xem', value: 2840, change: '+18%', icon: 'eye', tone: 'green' },
    { id: 'contacts', label: 'Lượt liên hệ', value: 147, change: '5.2% CR', icon: 'message', tone: 'orange' },
  ],
  weeklyInteractions: [
    { day: 'Thứ 2', views: 300, contacts: 12 },
    { day: 'Thứ 3', views: 420, contacts: 24 },
    { day: 'Thứ 4', views: 380, contacts: 18 },
    { day: 'Thứ 5', views: 520, contacts: 30 },
    { day: 'Thứ 6', views: 480, contacts: 28 },
    { day: 'Thứ 7', views: 640, contacts: 36 },
    { day: 'CN', views: 410, contacts: 20 },
  ],
  roomStatus: [
    { label: 'Đã thuê', value: 22, color: '#5f9f1b' },
    { label: 'Trống', value: 8, color: '#ef4b12' },
    { label: 'Thương lượng', value: 4, color: '#f8d5c6' },
  ],
  postPerformance: [
    { label: 'Lê Lợi', value: 590 },
    { label: 'Nguyễn Trãi', value: 980 },
    { label: 'Studio Q1', value: 500 },
    { label: 'Phòng full NT', value: 710 },
    { label: 'Căn hộ mini', value: 300 },
    { label: 'Trọ SV', value: 180 },
  ],
  roomDetails: [
    { id: 'P.101', post: 'Phòng trọ Lê Lợi', price: 2500000, views: 320, status: 'rented' },
    { id: 'P.102', post: 'Phòng trọ Lê Lợi', price: 2500000, views: 280, status: 'available' },
    { id: 'P.201', post: 'Mini studio Nguyễn Trãi', price: 4200000, views: 510, status: 'rented' },
    { id: 'P.202', post: 'Mini studio Nguyễn Trãi', price: 4200000, views: 490, status: 'negotiating' },
    { id: 'P.301', post: 'Phòng full nội thất Q1', price: 5800000, views: 720, status: 'rented' },
  ],
};
