import { ADMIN_STATUS } from '../models/adminModels';

export const adminDashboardMockData = {
  currentUser: {
    name: 'Quản trị viên',
    initials: 'AD',
  },
  pageHeader: {
    title: 'Tổng quan',
    highlight: 'quan',
    subtitle: 'Chào mừng trở lại, quản trị viên. Hệ thống đang hoạt động bình thường',
  },
  stats: [
    {
      id: 'revenue',
      label: 'Tổng doanh thu',
      value: 203444235,
      format: 'currency',
      trend: 'up',
      trendLabel: '12.4%',
      changeLabel: 'So với tháng trước',
      icon: 'dollar-sign',
      isPrimary: true,
      linkLabel: 'Xem chi tiết',
    },
    {
      id: 'users',
      label: 'Tổng người dùng',
      value: 2395,
      trend: 'up',
      trendLabel: '8.2%',
      changeLabel: 'Tăng trưởng tháng này',
      icon: 'users',
      linkLabel: 'Xem chi tiết',
    },
    {
      id: 'posts',
      label: 'Tổng bài đăng',
      value: 1305,
      trend: 'down',
      trendLabel: '2.1%',
      changeLabel: 'Giảm nhẹ tháng này',
      icon: 'file-text',
      linkLabel: 'Xem chi tiết',
    },
  ],
  performance: {
    title: 'Hiệu suất',
    years: ['2025', '2024'],
    labels: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
    seriesByYear: {
      2025: [
        {
          id: 'revenue',
          label: 'Doanh thu',
          color: '#D45B13',
          fillColor: 'rgba(212, 91, 19, 0.14)',
          points: [28, 42, 50, 46, 65, 68, 60, 72, 82, 100, 110, 125],
        },
        {
          id: 'rooms',
          label: 'Phòng',
          color: '#22c55e',
          fillColor: 'rgba(34, 197, 94, 0.12)',
          points: [12, 22, 32, 38, 50, 48, 44, 58, 66, 80, 90, 105],
        },
      ],
      2024: [
        {
          id: 'revenue',
          label: 'Doanh thu',
          color: '#D45B13',
          fillColor: 'rgba(212, 91, 19, 0.14)',
          points: [20, 34, 44, 48, 54, 60, 62, 70, 76, 84, 92, 103],
        },
        {
          id: 'rooms',
          label: 'Phòng',
          color: '#22c55e',
          fillColor: 'rgba(34, 197, 94, 0.12)',
          points: [10, 18, 24, 28, 35, 42, 48, 50, 54, 64, 72, 82],
        },
      ],
    },
  },
  staff: [
    {
      id: 1,
      username: 'admin',
      role: 'Quản trị cấp cao',
      roleTone: 'admin',
      status: ADMIN_STATUS.ONLINE,
      statusLabel: 'Trực tuyến',
      activity: 'Đang hoạt động',
    },
    {
      id: 2,
      username: 'manager_01',
      role: 'Quản lý',
      roleTone: 'manager',
      status: ADMIN_STATUS.ONLINE,
      statusLabel: 'Trực tuyến',
      activity: 'Xem báo cáo',
    },
    {
      id: 3,
      username: 'support_02',
      role: 'Hỗ trợ',
      roleTone: 'support',
      status: ADMIN_STATUS.OFFLINE,
      statusLabel: 'Ngoại tuyến',
      activity: '3 giờ trước',
      isMuted: true,
    },
    {
      id: 4,
      username: 'editor_03',
      role: 'Biên tập viên',
      roleTone: 'editor',
      status: ADMIN_STATUS.ONLINE,
      statusLabel: 'Trực tuyến',
      activity: 'Chỉnh sửa bài',
    },
  ],
  regions: [
    { id: 1, name: 'TP. Hồ Chí Minh', count: 486, icon: 'building-2' },
    { id: 2, name: 'Hà Nội', count: 312, icon: 'landmark' },
    { id: 3, name: 'Bình Dương', count: 198, icon: 'factory' },
    { id: 4, name: 'Long An', count: 145, icon: 'map-pin' },
    { id: 5, name: 'Cần Thơ', count: 112, icon: 'waves' },
  ],
  notifications: [
    {
      id: 1,
      author: 'KhanhDuy',
      initials: 'KD',
      message: 'yêu cầu cấp lại mật khẩu',
      time: '2 giờ trước',
      unread: true,
      tone: 'orange',
    },
    {
      id: 2,
      author: 'NguyenThu',
      initials: 'NT',
      message: 'vừa đăng 3 bài mới',
      time: '4 giờ trước',
      unread: true,
      tone: 'green',
    },
    {
      id: 3,
      author: 'MinhHoang',
      initials: 'MH',
      message: 'gửi khiếu nại mới',
      time: '6 giờ trước',
      unread: true,
      tone: 'rose',
    },
    {
      id: 4,
      author: 'Hệ thống',
      initials: 'HT',
      message: 'cập nhật thành công v2.4.1',
      time: 'Hôm qua',
      unread: false,
      tone: 'purple',
    },
  ],
  users: [
    { id: 'U001', username: 'hoang_long', email: 'long.hoang@gmail.com', role: 'owner', roleLabel: 'Chủ trọ', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U002', username: 'lan_anh', email: 'lananh99@gmail.com', role: 'tenant', roleLabel: 'Khách thuê', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U003', username: 'minh_quan', email: 'quan.minh@yahoo.com', role: 'tenant', roleLabel: 'Khách thuê', status: 'blocked', statusLabel: 'Bị khoá' },
    { id: 'U004', username: 'admin', email: 'admin@roomiematch.vn', role: 'admin', roleLabel: 'Quản trị viên', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U005', username: 'manager_01', email: 'manager01@roomiematch.vn', role: 'manager', roleLabel: 'Quản trị viên', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U006', username: 'support_02', email: 'support02@roomiematch.vn', role: 'support', roleLabel: 'Quản trị viên', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U007', username: 'editor_03', email: 'editor03@roomiematch.vn', role: 'editor', roleLabel: 'Quản trị viên', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U008', username: 'quoc_bao', email: 'bao.quoc@gmail.com', role: 'owner', roleLabel: 'Chủ trọ', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U009', username: 'thu_hang', email: 'hang.thu@hotmail.com', role: 'tenant', roleLabel: 'Khách thuê', status: 'active', statusLabel: 'Đang hoạt động' },
    { id: 'U010', username: 'viet_anh', email: 'vietanh.nguyen@outlook.com', role: 'owner', roleLabel: 'Chủ trọ', status: 'blocked', statusLabel: 'Bị khoá' },
  ],
  posts: [
    {
      id: 'P001',
      title: 'Phòng trọ khép kín full nội thất Quận 7 gần Lotte',
      author: 'hoang_long',
      date: '01/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 245,
      likes: 38,
      comments: 12,
      isFeatured: false,
      description: 'Phòng khép kín có cửa sổ lớn, đầy đủ giường, tủ, máy lạnh và khu bếp nhỏ. Vị trí gần Lotte Mart Quận 7, phù hợp sinh viên hoặc nhân viên văn phòng thuê dài hạn.',
    },
    {
      id: 'P002',
      title: 'Tìm nam ở ghép căn hộ Vinhomes Central Park Bình Thạnh',
      author: 'lan_anh',
      date: '03/06/2026',
      status: 'pending',
      statusLabel: 'Chờ duyệt',
      views: 89,
      likes: 14,
      comments: 3,
      isFeatured: false,
      description: 'Căn hộ đang trống một phòng nhỏ, cần tìm bạn nam ở ghép sạch sẽ, giờ giấc ổn định. Chi phí chia đều theo tháng, có thể dọn vào từ giữa tháng.',
    },
    {
      id: 'P003',
      title: 'Căn hộ dịch vụ studio sang xịn mịn Cầu Giấy Hà Nội',
      author: 'quoc_bao',
      date: '02/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 520,
      likes: 92,
      comments: 24,
      isFeatured: true,
      description: 'Studio mới hoàn thiện, có thang máy, bảo vệ, máy giặt riêng và khu bếp tiện nghi. Nằm gần nhiều trường đại học và tuyến xe buýt lớn tại Cầu Giấy.',
    },
    {
      id: 'P004',
      title: 'Phòng trọ giá rẻ cho sinh viên gần ĐH Bách Khoa',
      author: 'viet_anh',
      date: '28/05/2026',
      status: 'rejected',
      statusLabel: 'Bị từ chối',
      views: 12,
      likes: 0,
      comments: 0,
      isFeatured: false,
      description: 'Bài đăng bị từ chối do thiếu hình ảnh thực tế và thông tin giá điện nước. Chủ bài cần bổ sung mô tả rõ hơn trước khi gửi duyệt lại.',
    },
    {
      id: 'P005',
      title: 'Nhà nguyên căn 3 phòng ngủ Quận 9 giá tốt',
      author: 'hoang_long',
      date: '30/05/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 312,
      likes: 45,
      comments: 8,
      isFeatured: false,
      description: 'Nhà nguyên căn có sân để xe, 3 phòng ngủ, 2 nhà vệ sinh và bếp riêng. Phù hợp nhóm bạn hoặc gia đình nhỏ cần không gian riêng tại Quận 9.',
    },
    {
      id: 'P006',
      title: 'Tìm nữ ở ghép phòng trọ Gò Vấp, chung chủ',
      author: 'thu_hang',
      date: '04/06/2026',
      status: 'pending',
      statusLabel: 'Chờ duyệt',
      views: 42,
      likes: 5,
      comments: 1,
      isFeatured: false,
      description: 'Phòng đang có một nữ sinh viên ở, cần tìm thêm một bạn nữ ở ghép. Khu vực an ninh, gần chợ, gần trạm xe buýt và có giờ giấc rõ ràng.',
    },
    {
      id: 'P007',
      title: 'Phòng trọ cao cấp Tân Bình ban công thoáng mát',
      author: 'quoc_bao',
      date: '05/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 156,
      likes: 21,
      comments: 5,
      isFeatured: true,
      description: 'Phòng mới xây, có ban công riêng, cửa sổ lớn, máy lạnh và máy nước nóng. Khu dân cư yên tĩnh, thuận tiện di chuyển ra sân bay Tân Sơn Nhất.',
    },
    {
      id: 'P008',
      title: 'Căn hộ mini Hoàng Mai giá học sinh',
      author: 'viet_anh',
      date: '25/05/2026',
      status: 'rejected',
      statusLabel: 'Bị từ chối',
      views: 8,
      likes: 0,
      comments: 0,
      isFeatured: false,
      description: 'Bài đăng bị từ chối do nội dung mô tả chưa khớp với hình ảnh và chưa có thông tin liên hệ xác thực.',
    },
    {
      id: 'P009',
      title: 'Phòng gần Đại học Sư phạm Kỹ thuật Thủ Đức có gác lửng',
      author: 'minh_quan',
      date: '06/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 198,
      likes: 33,
      comments: 7,
      isFeatured: false,
      description: 'Phòng có gác lửng rộng, nhà vệ sinh riêng, wifi tốc độ cao và chỗ để xe trong nhà. Đi bộ vài phút đến khu ăn uống sinh viên.',
    },
    {
      id: 'P010',
      title: 'Tìm bạn ở ghép căn hộ 2 phòng ngủ tại Mỹ Đình',
      author: 'lan_anh',
      date: '07/06/2026',
      status: 'pending',
      statusLabel: 'Chờ duyệt',
      views: 64,
      likes: 9,
      comments: 2,
      isFeatured: false,
      description: 'Căn hộ có phòng khách, bếp, máy giặt và ban công phơi đồ. Cần tìm bạn ở ghép lịch sự, ưu tiên người đi làm văn phòng.',
    },
    {
      id: 'P011',
      title: 'Phòng trọ mới xây gần Khu công nghệ cao Quận 9',
      author: 'hoang_long',
      date: '08/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 430,
      likes: 76,
      comments: 18,
      isFeatured: true,
      description: 'Phòng mới xây, có thang máy, camera an ninh, khóa vân tay và khu giặt phơi riêng. Phù hợp nhân viên làm việc tại Khu công nghệ cao.',
    },
    {
      id: 'P012',
      title: 'Cho thuê phòng nhỏ gần chợ Bà Chiểu giá tiết kiệm',
      author: 'thu_hang',
      date: '09/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 121,
      likes: 17,
      comments: 4,
      isFeatured: false,
      description: 'Phòng nhỏ nhưng sạch sẽ, phù hợp một người ở. Gần chợ, cửa hàng tiện lợi và các tuyến xe buýt đi trung tâm.',
    },
    {
      id: 'P013',
      title: 'Cần tìm người thuê lại phòng studio Quận 3',
      author: 'admin',
      date: '10/06/2026',
      status: 'pending',
      statusLabel: 'Chờ duyệt',
      views: 73,
      likes: 11,
      comments: 2,
      isFeatured: false,
      description: 'Người đăng cần chuyển đi sớm nên muốn nhượng lại phòng studio còn hợp đồng. Bài đang chờ xác minh giấy tờ thuê phòng.',
    },
    {
      id: 'P014',
      title: 'Phòng trọ có thú cưng được phép ở Quận Bình Thạnh',
      author: 'quoc_bao',
      date: '11/06/2026',
      status: 'approved',
      statusLabel: 'Đã duyệt',
      views: 275,
      likes: 58,
      comments: 16,
      isFeatured: false,
      description: 'Phòng cho phép nuôi thú cưng nhỏ, có ban công thoáng, khu vực yên tĩnh và chủ nhà thân thiện. Phí vệ sinh được thỏa thuận riêng.',
    },
    {
      id: 'P015',
      title: 'Bài đăng phòng trọ thiếu địa chỉ chi tiết',
      author: 'viet_anh',
      date: '12/06/2026',
      status: 'rejected',
      statusLabel: 'Bị từ chối',
      views: 19,
      likes: 1,
      comments: 0,
      isFeatured: false,
      description: 'Bài đăng bị từ chối vì thiếu địa chỉ cụ thể, thiếu ảnh mặt tiền và thông tin chủ phòng chưa được xác minh.',
    },
  ],
  rooms: [
    { id: 'R001', area: 'Quận 7, TP. HCM', owner: 'hoang_long', status: 'available', statusLabel: 'Trống', capacity: 2, roomType: 'phong_don', roomTypeLabel: 'Phòng đơn', totalRooms: 5 },
    { id: 'R002', area: 'Bình Thạnh, TP. HCM', owner: 'lan_anh', status: 'renting', statusLabel: 'Đang thuê', capacity: 3, roomType: 'ghep', roomTypeLabel: 'Ở ghép', totalRooms: 1 },
    { id: 'R003', area: 'Cầu Giấy, Hà Nội', owner: 'quoc_bao', status: 'available', statusLabel: 'Trống', capacity: 2, roomType: 'can_ho', roomTypeLabel: 'Căn hộ', totalRooms: 8 },
    { id: 'R004', area: 'Hai Bà Trưng, Hà Nội', owner: 'viet_anh', status: 'inactive', statusLabel: 'Tạm ngưng', capacity: 1, roomType: 'phong_don', roomTypeLabel: 'Phòng đơn', totalRooms: 3 },
    { id: 'R005', area: 'Quận 9, TP. HCM', owner: 'hoang_long', status: 'renting', statusLabel: 'Đang thuê', capacity: 4, roomType: 'can_ho', roomTypeLabel: 'Căn hộ', totalRooms: 2 },
    { id: 'R006', area: 'Gò Vấp, TP. HCM', owner: 'thu_hang', status: 'pending', statusLabel: 'Chờ duyệt', capacity: 2, roomType: 'ghep', roomTypeLabel: 'Ở ghép', totalRooms: 1 },
  ],
  packages: [
    { id: 'PKG001', name: 'Gói Đăng Tin VIP 1', icon: 'file-text', targetCustomer: 'owner', targetCustomerLabel: 'Chủ trọ', pricePerMonth: 299000, duration: '30 ngày', features: ['Đăng tin nổi bật', 'Hiển thị ưu tiên đầu trang', 'Hỗ trợ duyệt nhanh trong 1h', 'Thống kê lượt xem chi tiết'], totalPurchased: 245, status: 'active', statusLabel: 'Đang bán' },
    { id: 'PKG002', name: 'Gói Đẩy Tin Tự Động', icon: 'activity', targetCustomer: 'owner', targetCustomerLabel: 'Chủ trọ', pricePerMonth: 149000, duration: '15 ngày', features: ['Đẩy tin tự động 2 lần/ngày', 'Huy hiệu tin nổi bật màu cam', 'Hỗ trợ tư vấn tối ưu tin đăng'], totalPurchased: 589, status: 'active', statusLabel: 'Đang bán' },
    { id: 'PKG003', name: 'Gói Tìm Bạn Ở Ghép Pro', icon: 'users', targetCustomer: 'tenant', targetCustomerLabel: 'Khách thuê', pricePerMonth: 49000, duration: '30 ngày', features: ['Hiển thị hồ sơ tìm bạn ở ghép nổi bật', 'Gửi lời mời trực tiếp đến 20 người', 'Hỗ trợ AI gợi ý bạn cùng phòng'], totalPurchased: 1042, status: 'active', statusLabel: 'Đang bán' },
    { id: 'PKG004', name: 'Gói VIP Toàn Diện', icon: 'shield', targetCustomer: 'owner', targetCustomerLabel: 'Chủ trọ', pricePerMonth: 599000, duration: '30 ngày', features: ['Đăng tin không giới hạn', 'Đẩy tin tự động mỗi 4h', 'Huy hiệu xác minh tài khoản uy tín', 'Tặng gói quảng cáo Facebook Group'], totalPurchased: 89, status: 'suspended', statusLabel: 'Tạm ngưng' },
  ],
  categories: {
    area: [
      { id: 'CAT_A01', name: 'TP. Hồ Chí Minh', priceRange: '2.5M - 8M ₫', creator: 'admin', quantity: 486 },
      { id: 'CAT_A02', name: 'Hà Nội', priceRange: '2M - 7M ₫', creator: 'admin', quantity: 312 },
      { id: 'CAT_A03', name: 'Bình Dương', priceRange: '1.5M - 4M ₫', creator: 'admin', quantity: 198 },
      { id: 'CAT_A04', name: 'Cần Thơ', priceRange: '1.2M - 3M ₫', creator: 'admin', quantity: 112 },
    ],
    roomType: [
      { id: 'CAT_RT01', name: 'Phòng đơn', priceRange: '1.5M - 4.5M ₫', creator: 'admin', quantity: 654 },
      { id: 'CAT_RT02', name: 'Căn hộ', priceRange: '5M - 15M ₫', creator: 'admin', quantity: 320 },
      { id: 'CAT_RT03', name: 'Ở ghép', priceRange: '800k - 2M ₫', creator: 'admin', quantity: 412 },
    ],
    utility: [
      { id: 'CAT_UT01', name: 'Máy lạnh', priceRange: 'N/A', creator: 'admin', quantity: 875 },
      { id: 'CAT_UT02', name: 'Máy giặt', priceRange: 'N/A', creator: 'admin', quantity: 620 },
      { id: 'CAT_UT03', name: 'Bảo vệ 24/7', priceRange: 'N/A', creator: 'admin', quantity: 410 },
      { id: 'CAT_UT04', name: 'Ban công', priceRange: 'N/A', creator: 'admin', quantity: 380 },
    ],
  },
  orders: [
    { id: 'ORD001', username: 'hoang_long', email: 'long.hoang@gmail.com', packageName: 'Gói Đăng Tin VIP 1', price: 299000, status: 'success', statusLabel: 'Thành công', date: '05/06/2026' },
    { id: 'ORD002', username: 'lan_anh', email: 'lananh99@gmail.com', packageName: 'Gói Tìm Bạn Ở Ghép Pro', price: 49000, status: 'success', statusLabel: 'Thành công', date: '04/06/2026' },
    { id: 'ORD003', username: 'quoc_bao', email: 'bao.quoc@gmail.com', packageName: 'Gói VIP Toàn Diện', price: 599000, status: 'pending', statusLabel: 'Chờ thanh toán', date: '06/06/2026' },
    { id: 'ORD004', username: 'thu_hang', email: 'hang.thu@hotmail.com', packageName: 'Gói Đẩy Tin Tự Động', price: 149000, status: 'failed', statusLabel: 'Thất bại', date: '02/06/2026' },
    { id: 'ORD005', username: 'viet_anh', email: 'vietanh.nguyen@outlook.com', packageName: 'Gói Đăng Tin VIP 1', price: 299000, status: 'success', statusLabel: 'Thành công', date: '01/06/2026' },
  ],
  complaints: [
    { id: 'CMP001', sender: 'lan_anh', type: 'Tin đăng sai sự thật', priority: 'high', priorityLabel: 'Cao', status: 'pending', statusLabel: 'Chờ xử lý', assignee: 'Chưa giao', date: '05/06/2026' },
    { id: 'CMP002', sender: 'minh_quan', type: 'Chủ trọ lừa đảo tiền cọc', priority: 'high', priorityLabel: 'Cao', status: 'processing', statusLabel: 'Đang xử lý', assignee: 'support_02', date: '04/06/2026' },
    { id: 'CMP003', sender: 'thu_hang', type: 'Phòng không giống ảnh', priority: 'medium', priorityLabel: 'Trung bình', status: 'resolved', statusLabel: 'Đã giải quyết', assignee: 'support_02', date: '31/05/2026' },
    { id: 'CMP004', sender: 'hoang_long', type: 'Người thuê làm ồn', priority: 'low', priorityLabel: 'Thấp', status: 'rejected', statusLabel: 'Từ chối', assignee: 'manager_01', date: '02/06/2026' },
  ],
  analytics: {
    monthlyUsers: {
      labels: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
      series: [
        { label: 'Tổng người dùng', color: '#4F6EF7', points: [1000, 1150, 1300, 1500, 1750, 1900, 2050, 2150, 2200, 2280, 2350, 2395] },
        { label: 'Người dùng mới', color: '#22c55e', points: [120, 150, 180, 220, 260, 180, 170, 140, 110, 120, 100, 95] },
        { label: 'Tài khoản bị khoá', color: '#f43f5e', points: [5, 8, 12, 10, 15, 6, 8, 12, 14, 9, 11, 7] },
      ]
    },
    monthlyPosts: {
      labels: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
      series: [
        { label: 'Đã duyệt', color: '#22c55e', points: [80, 95, 110, 130, 150, 140, 130, 155, 160, 170, 185, 190] },
        { label: 'Đang chờ duyệt', color: '#f59e0b', points: [12, 18, 15, 22, 28, 25, 20, 24, 30, 18, 22, 15] },
        { label: 'Bị từ chối', color: '#f43f5e', points: [5, 6, 8, 10, 12, 8, 11, 9, 14, 10, 8, 6] },
      ]
    },
    categoriesDistribution: {
      area: [
        { name: 'TP. Hồ Chí Minh', value: 45 },
        { name: 'Hà Nội', value: 30 },
        { name: 'Bình Dương', value: 15 },
        { name: 'Khác', value: 10 },
      ],
      roomType: [
        { name: 'Phòng đơn', value: 55 },
        { name: 'Căn hộ', value: 25 },
        { name: 'Ở ghép', value: 20 },
      ],
      priceRange: [
        { name: 'Dưới 2 triệu', value: 25 },
        { name: '2 - 5 triệu', value: 50 },
        { name: 'Trên 5 triệu', value: 25 },
      ]
    },
    revenue: {
      labels: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
      total: 203444235,
      points: [12000000, 14500000, 16000000, 15500000, 18000000, 20500000, 19000000, 22000000, 25000000, 28000000, 31000000, 33444235]
    },
    complaints: {
      labels: ['Đã giải quyết', 'Đang xử lý', 'Chưa giải quyết'],
      points: [65, 20, 15],
      colors: ['#22c55e', '#f59e0b', '#f43f5e']
    }
  }
};
